### PR TITLE
find_formula: fix when arg "correlation" defined outside of lme()

### LINKED ISSUE #482: lme models are funky when co/variance structures are not in the main call
This is some weird behavior...
``` r
library(nlme)


cr <- corAR1(form = ~ 1 | Mare)
fm1 <- lme(follicles ~ sin(2*pi*Time) + cos(2*pi*Time), Ovary,
           correlation = cr)

insight::find_formula(fm1)
#> Error: object of type 'symbol' is not subsettable


fm2 <- lme(follicles ~ sin(2*pi*Time) + cos(2*pi*Time), Ovary,
           correlation = corAR1(form = ~ 1 | Mare))
insight::find_formula(fm2)
#> $conditional
#> follicles ~ sin(2 * pi * Time) + cos(2 * pi * Time)
#> <environment: 0x0000000012376068>
#> 
#> $correlation
#> ~1 | Mare
#> <environment: 0x0000000012376068>
#> 
#> attr(,"class")
#> [1] "insight_formula" "list"
```

<sup>Created on 2022-01-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #482 

```r
library(nlme)
cr <- corAR1(form = ~ 1 | Mare)
fm1 <- lme(follicles ~ sin(2*pi*Time) + cos(2*pi*Time), Ovary,
           correlation = cr)
insight::find_formula(fm1)

$conditional
follicles ~ sin(2 * pi * Time) + cos(2 * pi * Time)
<environment: 0x0000024c7b2e5e28>

$correlation
~1 | Mare

attr(,"class")
[1] "insight_formula" "list"           

fm2 <- lme(follicles ~ sin(2*pi*Time) + cos(2*pi*Time), Ovary,
           correlation = corAR1(form = ~ 1 | Mare))
insight::find_formula(fm2)

$conditional
follicles ~ sin(2 * pi * Time) + cos(2 * pi * Time)
<environment: 0x0000024c6fa4b718>

$correlation
~1 | Mare
<environment: 0x0000024c6fa4b718>

attr(,"class")
[1] "insight_formula" "list" 
```

### CODE REVIEW

**Comment by etiennebacher** [comment]
Just noticed that this problem also appeared with `gls()`, I added a fix for that as well.

**Comment by strengejacke** [comment]
Thanks! I see that you ue `class(fcorr) ==` - can we be certain that `fcorr` always inherits from only one class? Sometimes, an object has multiple class attributes and then the if-statement would warn/fail. I suggest using `class(fcorr)[1]` instead.

**Comment by etiennebacher** [comment]
Right, I replaced `class(fcorr) ==` by `inherits(fcorr, ...)` because the class "name" is not necessarily the first class.

**Comment by bwiernik** [comment]
You should always use inherits() for checking classes, never == or %in%

**Pull request merged**
