### PR TITLE
switch to poorman

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
cf. https://github.com/easystats/easystats/issues/168

Also
- spell check
- style
- reknit README

### CODE REVIEW

**Comment by strengejacke** [comment]
@IndrajeetPatil can you take a look at this?
https://github.com/easystats/insight/runs/4193558264?check_suite_focus=true

**Comment by IndrajeetPatil** [comment]
Yes, already on it:
https://github.com/nathaneastwood/poorman/issues/94

**Comment by strengejacke** [comment]
ah, cool! but nonetheless, if used conditionally, there should be no error at all, so the issue is still something to be addressed from our side.

**Comment by strengejacke** [comment]
Line 22 in display.rmd needs to be in an else-statement

**Pull request merged**
