### PR TITLE
tidy description; styling

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by strengejacke** [comment]
That PR broke working examples. (export_table)

**Comment by strengejacke** [comment]
That's why I'm hesitant against using styler or linter packages, I don't believe these are 100% reliable.

**Comment by IndrajeetPatil** [comment]
I don't understand how can all github actions pass when the examples are failing?!

**Comment by IndrajeetPatil** [comment]
Where do you see that the example is broken?

**Comment by strengejacke** [comment]
That's the even worse thing that things might no longer work, and this remains undetected:

``` r
library(insight)

# before "styling"
data(iris)
x <- as.data.frame(iris[1:5, ])
attr(x, "table_footer") <- list(
  c("\nA yellow line", "yellow"),
  c("\nAnd a red line", "red"),
  c("\nAnd a blue line", "blue")
)
cat(export_table(x))
#> Sepal.Length | Sepal.Width | Petal.Length | Petal.Width | Species
#> -----------------------------------------------------------------
#>         5.10 |        3.50 |         1.40 |        0.20 |  setosa
#>         4.90 |        3.00 |         1.40 |        0.20 |  setosa
#>         4.70 |        3.20 |         1.30 |        0.20 |  setosa
#>         4.60 |        3.10 |         1.50 |        0.20 |  setosa
#>         5.00 |        3.60 |         1.40 |        0.20 |  setosa
#> 
#> A yellow line
#> And a red line
#> And a blue line


# after styling
x <- as.data.frame(iris[1:5, ])
attr(x, "table_footer") <- list(
  c("\\nA yellow line", "yellow"),
  c("\\nAnd a red line", "red"),
  c("\\nAnd a blue line", "blue")
)
cat(export_table(x))
#> Sepal.Length | Sepal.Width | Petal.Length | Petal.Width | Species
#> -----------------------------------------------------------------
#>         5.10 |        3.50 |         1.40 |        0.20 |  setosa
#>         4.90 |        3.00 |         1.40 |        0.20 |  setosa
#>         4.70 |        3.20 |         1.30 |        0.20 |  setosa
#>         4.60 |        3.10 |         1.50 |        0.20 |  setosa
#>         5.00 |        3.60 |         1.40 |        0.20 |  setosa
#> \nA yellow line\nAnd a red line\nAnd a blue line
```

<sup>Created on 2021-02-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
This is definitely a bug in `styler`. I will raise an issue about it there. In the meanwhile, I will fix the example manually.

**Pull request merged**
