### PR TITLE
works?

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by strengejacke** [comment]
I think you have to check this locally (with "correct" CRAN settings), or via win-builder. I don't think GitHub is properly configured to find issues here.

**Comment by IndrajeetPatil** [comment]
Okay, I am sending this to winbuilder, and you should receive an email about it.

**Comment by strengejacke** [comment]
Seems to work! Local checks and win-builder found no issues. Maybe we can submit with this "usecase"?

**Comment by IndrajeetPatil** [comment]
Absolutely. If we don't get any further issues from CRAN or from users related to this, we can start using the function in other packages as well.

**Pull request merged**
