### PR TITLE
Satterthwaite dof for `get_predicted.merMod`

### PR DESCRIPTION
**Pull request by vincentarelbundock**
This is a work in progress implementation of Satterthwaite degrees of freedom for use when applying `get_predited()` to `lmerMod` models.

Question: Should I include a new `dof` argument in the method signature for `get_predicted.lmerMod`?

Currently this produces the same results as `emmeans`:

``` r
library(lme4)
library(insight)
library(emmeans)
data(sleepstudy)

mod <- lmer(Reaction ~ Days + (1 + Days | Subject), data = sleepstudy)

ins <- get_predicted(
  mod,
  dof = "satterthwaite",
  include_random = FALSE,
  data = data.frame(Days = sleepstudy$Days,
                    Reaction = 10,
                    Subject = 308)) |> data.frame()

emm <- ref_grid(
  object = mod,
  specs = ~ Days,
  at = list(Days = sleepstudy$Days, Subject = 308),
  lmer.df = "satterthwaite") |> confint()

head(ins)
#>   Predicted       SE   CI_low  CI_high
#> 1  251.4051 6.824597 237.0064 265.8038
#> 2  261.8724 6.786929 247.5532 276.1916
#> 3  272.3397 7.094267 257.3721 287.3073
#> 4  282.8070 7.705438 266.5499 299.0640
#> 5  293.2742 8.555575 275.2235 311.3250
#> 6  303.7415 9.581277 283.5268 323.9563

head(emm)
#>   Days prediction       SE       df lower.CL upper.CL
#> 1    0   251.4051 6.824597 16.99973 237.0064 265.8038
#> 2    1   261.8724 6.786929 16.99972 247.5532 276.1916
#> 3    2   272.3397 7.094267 16.99973 257.3721 287.3073
#> 4    3   282.8070 7.705438 16.99975 266.5499 299.0640
#> 5    4   293.2742 8.555575 16.99977 275.2235 311.3250
#> 6    5   303.7415 9.581277 16.99980 283.5268 323.9563
```

### CODE REVIEW

**Comment by bwiernik** [comment]
The argument used in parameters for invoking satterthwaite is `ci_method`

**Comment by vincentarelbundock** [comment]
I’m writing some tests for an implementation of Satterthwaite/Kenward-Roger in `insight::get_predicted`, and wondering if it’s normal that `emmeans` sometimes produces different standard errors for different values of the `lmer.df` argument. Perhaps an `emmeans` expert like @mattansb will know.

Compare the `SE` columns in those those examples:

``` r
library(emmeans)
library(lme4)

sleepstudy$mygrp <- sample(1:5, size = 180, replace = TRUE)
sleepstudy$mysubgrp <- NA
for (i in 1:5) {
    filter_group <- sleepstudy$mygrp == i
    sleepstudy$mysubgrp[filter_group] <- sample(1:30, size = sum(filter_group), replace = TRUE)
}

mod <- lme4::lmer(Reaction ~ Days + (1 | mygrp / mysubgrp) + (1 | Subject), data = sleepstudy)
#> boundary (singular) fit: see help('isSingular')
 
em_sa <- ref_grid(object = mod, specs = ~ Days, at = list(Days = 1:3), lmer.df = "satterthwaite")
em_kr <- ref_grid(object = mod, specs = ~ Days, at = list(Days = 1:3), lmer.df = "kenward-roger")

confint(em_sa) |> data.frame()
#>   Days prediction       SE       df lower.CL upper.CL
#> 1    1   261.8724 9.477568 20.42799 242.1290 281.6157
#> 2    2   272.3397 9.270581 18.71470 252.9161 291.7633
#> 3    3   282.8070 9.129983 17.60890 263.5950 302.0189

confint(em_kr) |> data.frame()
#>   Days prediction       SE       df lower.CL upper.CL
#> 1    1   261.8724 9.510457 19.97973 242.0326 281.7121
#> 2    2   272.3397 9.290239 18.31181 252.8454 291.8340
#> 3    3   282.8070 9.140798 17.23437 263.5415 302.0724
```

**Comment by mattansb** [comment]
This is expected, since the KR method adjusts the vcov matrix (something the S method does not). Similar differences can be seen when using the `lmerTest` package.

**Comment by strengejacke** [comment]
Looking at this (great) PR, I think we can probably "merge" `parameters::degrees_of_freedom()` and `insight::get_df()`? Currently, the method in _parameters_ are quite well tested, I'd say, and very robust. I'm not sure if `get_df()` is en par with `degrees_of_freedom()`.

**Comment by vincentarelbundock** [comment]
> Looking at this (great) PR, I think we can probably "merge" `parameters::degrees_of_freedom()` and `insight::get_df()`? Currently, the method in _parameters_ are quite well tested, I'd say, and very robust. I'm not sure if `get_df()` is en par with `degrees_of_freedom()`.

Right, that perhaps makes sense.

I'm over my "open source time allocation" this week, so I probably won't have time to engage with that in the near future. So it might make sense to just finish this PR first, and then move with `degrees_of_freedom` in the future when one of us finds time.

If all the current tests pass, I think this is ready for a review + touch-ups + merge.

**Comment by strengejacke** [comment]
> in the future when one of us finds time.

Yeah, it's not urgent. It's at the moment just a bit annoying to take care of adding the same features in two different packages ;-)

**Comment by vincentarelbundock** [comment]
absolutely

**Comment by vincentarelbundock** [comment]
Looks like the tests pass. I will leave this here a while in case anyone wants to look at it before merge.

Note that many files have changed, but this is mostly because I have consolidated the `get_predicted` and `get_predicted_ci` documentation. There are relatively few substantive code changes.

**Comment by strengejacke** [comment]
Looks good! One thing we could probably change are the `ci_method` options, to be in line with other packages (namely, _parameters_). I would say `"gaussian"` can be `"wald"` or `"normal"`.

**Comment by bwiernik** [comment]
This looks great to me. Thanks!

Two thoughts:

1. Do we want to use `dof` rather than `df` to be consistent with the short forms used in *parameters* and other R packages (and avoid potential confusion with the `df()` distribution function)?

2. Vincent should be changed from ctb to aut in DESCRIPTION

**Comment by strengejacke** [comment]
at 1 - you mean `get_dof()`?

at 2 - agree!

**Comment by strengejacke** [comment]
Maybe, in the long run, we can remove `dof()` from _parameters_ anyway, and only have `degrees_of_freedom()` as an alias for `get_df()`. To me, `get_df()` looks a bit clearer than `get_dof()` ;-)

**Comment by bwiernik** [comment]
Fair enough

**Pull request merged**
