### PR TITLE
Fix failing afex tests

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Yepp, it's still failing.

```r
── Error ('test-mixed.R:15:1'): (code run outside of `test_that()`) ────────────
<subscriptOutOfBoundsError/error/condition>
Error in `as.character(formula.f)[[2]]`: subscript out of bounds
Backtrace:
    ▆
 1. └─afex::mixed(Reaction ~ Days + (1 + Days | Subject), data = sleepstudy) at test-mixed.R:15:0

[ FAIL 1 | WARN 0 | SKIP 15 | PASS 3087 ]
```

**Comment by strengejacke** [comment]
Is this an afex issue?

**Comment by IndrajeetPatil** [comment]
I am not sure, but maybe one of the authors of _afex_ can help us out here. Hello, @mattansb 😄

**Comment by strengejacke** [comment]
Line 15 is failing. There's no insight-code involved until that line. But I cannot reproduce locally.

**Comment by mattansb** [comment]
Trying something to see if this is a scoping issue...

**Comment by mattansb** [comment]
Hey @singmann, any chance you know what's going on here, or can help?

**Comment by singmann** [comment]
No idea what this could be. I also cannot replicate it. This call essentially performs the following operation which should work without any issue: `as.character(as.formula(Reaction ~ Days + (1 + Days | Subject)))[[2]]`

I know there are sometimes weird scope issues when using `testthat`, but I cannot see how this would happen here. Sorry.

**Comment by mattansb** [comment]
Thanks @singmann - are you also running into similar testing issues in `afex`?

**Comment by singmann** [comment]
Not that I know. Haven't seen an error like this before.

**Comment by mattansb** [comment]
Well guys, that's all I've got (:

**Comment by mattansb** [comment]
@IndrajeetPatil maybe comment out this test :P

**Comment by IndrajeetPatil** [comment]
I agree. 

If the context of the failure is so esoteric and as rare as hen's teeth, we can remove the relevant tests without much apprehension.

**Pull request merged**
