### PR TITLE
fixes to insight when include_aov = F

### PR DESCRIPTION
**Pull request by mattansb**
Waiting for #400

### CODE REVIEW

**Comment by strengejacke** [comment]
@mattansb We have now

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure (test-aovlist.R:72:5): find_terms ───────────────────────────────────
find_terms(m1) (`actual`) not equal to list(response = "yield", conditional = c("N", "P", "K", "Error(block)")) (`expected`).

`actual` is length 3
`expected` is length 2

`names(actual)`:   "response" "conditional" "error"
`names(expected)`: "response" "conditional"        

`actual$conditional`:   "N" "P" "K" "N:P"          "N:K" "P:K" "N:P:K"
`expected$conditional`: "N" "P" "K" "Error(block)"                    

`actual$error` is a character vector ('Error(block)')
`expected$error` is absent
── Failure (test-aovlist.R:76:5): find_terms ───────────────────────────────────
find_terms(m1, flatten = TRUE) (`actual`) not equal to c("yield", "N", "P", "K", "Error(block)") (`expected`).

`names(actual)` is a character vector ('response', 'conditional1', 'conditional2', 'conditional3', 'conditional4', ...)
`names(expected)` is absent

`actual[2:9]`:   "N" "P" "K" "N:P" "N:K" "P:K" "N:P:K" "Error(block)"
`expected[2:5]`: "N" "P" "K"                           "Error(block)"
```

(see https://github.com/easystats/insight/pull/401/checks?check_run_id=3083533468) - is this expected?

**Comment by mattansb** [comment]
Right, I made a change to `find_terms` for `afex_aov` and `aovlist` objects to now return the error term under `$error` (it was previously giving weird results for complex error terms).

Why does this :

``` r
insight::find_terms(y ~ a * b)
#> $response
#> [1] "y"
#> 
#> $conditional
#> [1] "a" "b"
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Not also give `a:b` as a conditional term?

This is what `terms` gives:

``` r
attr(terms(y ~ a * b), "term.labels")
#> [1] "a"   "b"   "a:b"
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Can we merge this?

**Comment by mattansb** [comment]
No, still have my question about terms https://github.com/easystats/insight/pull/401#issuecomment-881990248

**Comment by strengejacke** [comment]
I think `find_terms()` was always intended to return all predictors/variables, while `find_parameters()` will return the parameters.

we have 
- `find_variables()`, which returns the "pure" variable names
- `find_terms()`, which returns the variable names, including patterns like `log()` etc.
- `find_parameters()`, which should return the parameters names similar to what `coef()` / `summary()` gives
-

**Comment by mattansb** [comment]
So it is intended that `find_terms` ignores interaction terms?

**Comment by mattansb** [comment]
@strengejacke I'm done (:

**Comment by strengejacke** [comment]
> So it is intended that find_terms ignores interaction terms?

Yes, the main intention was to find all "single" variables, but in that way how they entered the model (`log`, `I`, `scale`, ...).

**Pull request merged**
