### PR TITLE
find_/get_parameters

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
- [ ] make it work for brms for bayestestR
- [ ] make it better

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
I have missed your draft of the functions!

**Comment by DominiqueMakowski** [comment]
I would rename find_parameter to find_parameterS (as it general there are more than one parameter, at least the intercept and a slope)?

**Comment by DominiqueMakowski** [comment]
Naive question: why favour the term "conditional" over "fixed" or others?

**Comment by strengejacke** [comment]
I was thinking of it makes sense to keep the naming convention from the other functions. But I wasn't sure, either, if it's better to call it fixed? However, the `fixef()` for glmmTMB for instance, returns named lists, with names conditional etc.

**Comment by DominiqueMakowski** [comment]
I don't have a particularly strong opinion...  Although accurate mathematically, "conditional" always seemed kind of obscure and intuitive to me... But there are no real other options apparently (since fixed effects can refer to conditional parameters *and more*?)

**Comment by strengejacke** [comment]
Yes, to zero-inflated parameters, and for brms also to simplex-parameters etc.

**Pull request merged**
