### PR TITLE
Allow to show stars only for specific column

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
``` r
m <- brms::brm(mpg ~ wt, data=mtcars, prior = brms::set_prior("normal(0, 1)", class = "b"), refresh=0)
#> Compiling Stan program...
#> Start sampling
param <- parameters::parameters(m, test=c("pd", "BF"))
#> Warning: Bayes factors might not be precise.
#> For precise Bayes factors, sampling at least 40,000 posterior samples is recommended.

insight::format_table(param, stars="pd")
#>     Parameter   Component Median         95% CI      pd  Rhat     ESS       BF
#> 1 (Intercept) conditional  32.30 [27.68, 36.28] 100%*** 1.001 2272.00 1.73e+08
#> 2          wt conditional  -3.81 [-4.96, -2.39] 100%*** 1.000 2163.00 1.60e+03
#> 3       sigma       sigma   3.47 [ 2.65,  4.83] 100%*** 1.001 1779.00 4.36e+09
```

<sup>Created on 2022-10-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
It seems like the `stars` argument doens't propagate from `display()`, only for Bayesian models... but I cannot find at which level does it happen 

``` r
m <-lm(mpg ~ wt, data=mtcars)
insight::display(parameters::parameters(m), stars=TRUE)
```

| Parameter   | Coefficient |  SE  |     95% CI     | t(30) |       p       |
|:------------|:-----------:|:----:|:--------------:|:-----:|:-------------:|
| (Intercept) |    37.29    | 1.88 | (33.45, 41.12) | 19.86 | \< .001\*\*\* |
| wt          |    -5.34    | 0.56 | (-6.49, -4.20) | -9.56 | \< .001\*\*\* |

``` r

m <- brms::brm(mpg ~ wt, data=mtcars, prior = brms::set_prior("normal(0, 1)", class = "b"), refresh=0)
#> Compiling Stan program...
#> Start sampling
param <- parameters::parameters(m, test=c("pd", "BF"))
#> Warning: Bayes factors might not be precise.
#> For precise Bayes factors, sampling at least 40,000 posterior samples is recommended.

insight::format_table(param, stars=TRUE)
#>     Parameter   Component Median         95% CI      pd  Rhat     ESS
#> 1 (Intercept) conditional  32.41 [27.82, 36.16] 100%*** 1.000 2506.00
#> 2          wt conditional  -3.83 [-4.96, -2.46] 100%*** 1.000 2463.00
#> 3       sigma       sigma   3.43 [ 2.64,  4.81] 100%*** 1.000 2094.00
#>            BF
#> 1 5.42e+12***
#> 2 6.30e+03***
#> 3 1.54e+08***
insight::display(param, stars=TRUE)
```

| Parameter   | Median |     95% CI     |  pd  | Rhat  |   ESS   |    BF    |
|:------------|:------:|:--------------:|:----:|:-----:|:-------:|:--------:|
| (Intercept) | 32.41  | (27.82, 36.16) | 100% | 1.000 | 2506.00 | 5.42e+12 |
| wt          | -3.83  | (-4.96, -2.46) | 100% | 1.000 | 2463.00 | 6.30e+03 |

Fixed effects

| Parameter | Median |    95% CI    |  pd  | Rhat  |   ESS   |    BF    |
|:----------|:------:|:------------:|:----:|:-----:|:-------:|:--------:|
| sigma     |  3.43  | (2.64, 4.81) | 100% | 1.000 | 2094.00 | 1.54e+08 |

Fixed effects sigma

<sup>Created on 2022-10-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Review by strengejacke — CHANGES_REQUESTED** [review]
I think you need to handle the `stars` argument in other helper functions, too. E.g., if you provide a character vector, will this work in `.format_p_values()`?

**Review by strengejacke — CHANGES_REQUESTED** [review]
I think you need to handle the `stars` argument in other helper functions, too. E.g., if you provide a character vector, will this work in `.format_p_values()`?

**Comment by strengejacke** [comment]
> It seems like the stars argument doesn't propagate from display(), only for Bayesian models... but I cannot find at which level it happens

Was in _parameters_, the `print.parameters_stan()` method. should be fixed in _parameters 0.19.0.5_.

**Review by strengejacke — APPROVED** [review]

**Pull request merged**
