### PR TITLE
Update format_table.R

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by strengejacke** [comment]
😱

**Comment by strengejacke** [comment]
You know you're touching a well-established, for decades well-running system here?

**Comment by mattansb** [comment]
I've added some more tests - but it seems to be working as intended...

**Comment by mattansb** [comment]
The failing tests are unrelated.
If you feel safe, I think this can be merged (:

**Comment by strengejacke** [comment]
> The failing tests are unrelated.

No, I don't think so. See https://github.com/easystats/insight/runs/5526802904?check_suite_focus=true#step:10:324

**Comment by mattansb** [comment]
How's that?

**Comment by strengejacke** [comment]
Let's see if it works, and how vignettes/examples, e.g. in _parameters_, look like after merging this PR. :-)

**Pull request merged**
