### PR TITLE
revise get_priors.brmsfit

### LINKED ISSUE #332: get_priors for brms
https://github.com/easystats/insight/blob/f845b3aa802dd32cf99e08cd144e74bfe3caf455/R/get_priors.R#L256

should it be `NA` here?

(related to https://github.com/easystats/bayestestR/issues/409)

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
I forgot that we had #335 😅 

Fixes #332

I (hopefully) streamlined the code for brms objects

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
It seems to work 

```r
> library(brms)
> 
> 
> model <- brm(mpg ~ 0 + cyl, data = mtcars, algorithm = "fixed_param", refresh = 0)
Compiling Stan program...
Start sampling
Running MCMC with 1 chain...

Chain 1 finished in 0.0 seconds.
> insight::get_priors(model, effects = "all", components = "all")
  Parameter Distribution Location Scale df
1     b_cyl      uniform       NA    NA NA
2     sigma    student_t        0   5.4  3
> 
```
```r
> model <- brm(mpg ~ cyl, data = mtcars, algorithm = "fixed_param", refresh = 0)
Compiling Stan program...
Start sampling
Running MCMC with 1 chain...

Chain 1 finished in 0.0 seconds.
> insight::get_priors(model, effects = "all", components = "all")
    Parameter Distribution Location Scale df
1 b_Intercept    student_t     19.2   5.4  3
2       b_cyl      uniform       NA    NA NA
3       sigma    student_t      0.0   5.4  3
> 
```
```r
> model <- brm(mpg ~ cyl + (1|gear), data = mtcars, algorithm = "fixed_param", refresh = 0)
Compiling Stan program...
Start sampling
Running MCMC with 1 chain...

Chain 1 finished in 0.0 seconds.
> insight::get_priors(model, effects = "all", components = "all")
            Parameter Distribution Location Scale df
1         b_Intercept    student_t     19.2   5.4  3
2               b_cyl      uniform       NA    NA NA
3 r_gear.3.Intercept.         <NA>       NA    NA NA
4 r_gear.4.Intercept.         <NA>       NA    NA NA
5 r_gear.5.Intercept.         <NA>       NA    NA NA
6  sd_gear__Intercept    student_t      0.0   5.4  3
7               sigma    student_t      0.0   5.4  3
> 
> 
```
```r
> model <- brm(brms::brmsformula(
+   mpg ~ cyl + (1|G|gear),
+   sigma ~ 1 + (1|G|gear),
+   beta ~ 1 + (1|G|gear),
+   family = exgaussian()
+ ), data = mtcars, algorithm = "fixed_param", refresh = 0)
Compiling Stan program...
Start sampling
Running MCMC with 1 chain...

Chain 1 finished in 0.1 seconds.
> insight::get_priors(model, effects = "all", components = "all")
                                   Parameter Distribution Location Scale df
1                                b_Intercept    student_t     19.2   5.4  3
2                          b_sigma_Intercept    student_t      0.0   2.5  3
3                           b_beta_Intercept       normal      1.7   1.3 NA
4                                      b_cyl      uniform       NA    NA NA
5                                   r_1.1.1.         <NA>       NA    NA NA
6                                   r_1.2.1.         <NA>       NA    NA NA
7                                   r_1.3.1.         <NA>       NA    NA NA
8                                   r_1.1.2.         <NA>       NA    NA NA
9                                   r_1.2.2.         <NA>       NA    NA NA
10                                  r_1.3.2.         <NA>       NA    NA NA
11                                  r_1.1.3.         <NA>       NA    NA NA
12                                  r_1.2.3.         <NA>       NA    NA NA
13                                  r_1.3.3.         <NA>       NA    NA NA
14                       r_gear.3.Intercept.         <NA>       NA    NA NA
15                       r_gear.4.Intercept.         <NA>       NA    NA NA
16                       r_gear.5.Intercept.         <NA>       NA    NA NA
17                r_gear__sigma.3.Intercept.         <NA>       NA    NA NA
18                r_gear__sigma.4.Intercept.         <NA>       NA    NA NA
19                r_gear__sigma.5.Intercept.         <NA>       NA    NA NA
20                 r_gear__beta.3.Intercept.         <NA>       NA    NA NA
21                 r_gear__beta.4.Intercept.         <NA>       NA    NA NA
22                 r_gear__beta.5.Intercept.         <NA>       NA    NA NA
23                        sd_gear__Intercept    student_t      0.0   5.4  3
24                  sd_gear__sigma_Intercept    student_t      0.0   5.4  3
25                   sd_gear__beta_Intercept    student_t      0.0   5.4  3
26      cor_gear__Intercept__sigma_Intercept          lkj      1.0    NA NA
27       cor_gear__Intercept__beta_Intercept          lkj      1.0    NA NA
28 cor_gear__sigma_Intercept__beta_Intercept          lkj      1.0    NA NA
```

**Comment by DominiqueMakowski** [comment]
Missing features include: 
- dealing with other components of brmsprior, like `nlpar` and `bound`
- parameters related to random; what's their prior if any

**Comment by DominiqueMakowski** [comment]
There is another issue which I'm not sure how to fix:




```r
> model <- brm(mpg ~ s(wt), data = mtcars, algorithm = "fixed_param", refresh = 0)
> 
> insight::find_parameters(model, effects = "all", components = "all", flatten = TRUE)
[1] "b_Intercept" "bs_swt_1"    "sds_swt_1"   "sigma"      
```

For GAMs, the parameters are `bs_swt_1` and `sds_swt_1`, but the priors are presented as follows:

```
> brms::prior_summary(model)
                   prior     class  coef group resp dpar nlpar bound       source
                  (flat)         b                                        default
                  (flat)         b swt_1                             (vectorized)
 student_t(3, 19.2, 5.4) Intercept                                        default
    student_t(3, 0, 5.4)       sds                                        default
    student_t(3, 0, 5.4)       sds s(wt)                             (vectorized)
    student_t(3, 0, 5.4)     sigma                                        defaul
```

Which means that for class = `b` of GAMs, the class is actually `bs` (need to add an `s`), but I'm not sure how to detect that this prior corresponds to that of a smooth term... 

Moreover, for the parameter `sds_swt_1` It's unclear how to retrieve that from the priors' table, since the coef in it is written as `s(wt)` 😕

**Comment by strengejacke** [comment]
Do I need to review this, or can I trust you? 😬

**Comment by strengejacke** [comment]
jc0ll

**Comment by DominiqueMakowski** [comment]
Haha it needs your review as it's an inversion of the logic to match parameters and priors: previously we went from parameters to priors, and now it's from priors to parameters

**Comment by strengejacke** [comment]
Maybe just add a test that checks against expected output? Just reviewing the code currently doesn't help me judging whether everything works as intended. 

homer_dimishing

**Comment by strengejacke** [comment]
@DominiqueMakowski can we merge this?

**Comment by DominiqueMakowski** [comment]
Well no you wanted me to add some checks and tests which I'll do asap ;)

**Comment by DominiqueMakowski** [comment]
Here's a walkthrough with the hope that you see clearer:

```r
>   model <- brms::brm(mpg ~ wt, data = mtcars, seed = 1, refresh = 0)
>   as.data.frame(brms::prior_summary(model))
                    prior     class coef group resp dpar nlpar bound  source
1                                 b                                  default
2                                 b   wt                             default
3 student_t(3, 19.2, 5.4) Intercept                                  default
4    student_t(3, 0, 5.4)     sigma                                  default
```

so the `get_priors()` v2 first retrieves the models' priors table. However, when brms prints the table it actually does some additional useful stuff:

```r
> # See the difference with the 'printed' table:
>   brms::prior_summary(model)
                   prior     class coef group resp dpar nlpar bound       source
                  (flat)         b                                       default
                  (flat)         b   wt                             (vectorized)
 student_t(3, 19.2, 5.4) Intercept                                       default
    student_t(3, 0, 5.4)     sigma                                       default
```


So our get_priors then re-uses some internal brms function used for the printing of said brms table  to retrieve this info (e.g.,, to fill with the `(flat)`). That's probably the most obscure bits of code as it copies some brms internal functions used for the printing. This part could possibly be streamlined or even removed entirely but for now it worked 🤷‍♂️ 

From there, it does some pasting of columns together to attempt to find, to each prior, the expected parameter name. Which is added as a column to the table. **This information is saved in the output of get_priors** (as it's the key to everything):

```r
> priors <- insight::get_priors(model)
> attributes(priors)$priors
                    prior     class coef group resp dpar nlpar bound       source   Parameter
1                  (flat)         b                                       default          b_
2                  (flat)         b   wt                             (vectorized)        b_wt
3 student_t(3, 19.2, 5.4) Intercept                                       default b_Intercept
4    student_t(3, 0, 5.4)     sigma                                       default       sigma
```


Finally, it finds the actual parameters of the model, and then tries to find for each of them its matching prior based on this newly created "expected parameter name" column.

As Paul mentioned, the problem is that the naming scheme of the parameter is not consistent in respect to the priors info, so there might be edgecases etc. but afaik it's already far more stable than what it used to be.

Hope it's clearer!

I have added a test file but it requires to fit a brms model so I commented it all for now, not sure how to best deal with it (skip on cran?)

**Comment by strengejacke** [comment]
Ok, I think it's bit clearer to me now. Does this affect _bayestestR_?

**Comment by DominiqueMakowski** [comment]
> Does this affect bayestestR? 

Nope

**Comment by DominiqueMakowski** [comment]
I think you can merge this

**Comment by strengejacke** [comment]
ok, fingers crossed! :-)

**Pull request merged**
