### PR TITLE
Bump minimum needed R version to `R 3.6`

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
cf. https://github.com/easystats/easystats/issues/304

- `R 4.3` release is a month away (21st April).
- We don't test `R 3.5` in our CI/CD either.

### CODE REVIEW

**Comment by strengejacke** [comment]
I think we can ask @vincentarelbundock here and his R version dependencies. But for _modelsummary_, _parameters_ and _performance_ already require R 3.6, so maybe only _marginaleffects_ is affected?

**Comment by strengejacke** [comment]
https://cran.r-project.org/web/packages/marginaleffects/index.html

No, not affected. I think we can safely bump requirements to R3.6, and maybe @vincentarelbundock you do the same for _modelsummary_?

**Comment by vincentarelbundock** [comment]
> No, not affected. I think we can safely bump requirements to R3.6, and maybe @vincentarelbundock you do the same for _modelsummary_?

Sounds good. Thanks for the heads up!

**Comment by IndrajeetPatil** [comment]
@strengejacke Are we backporting anything from `R 3.5` that can be removed? Nothing comes to my mind, at least.

**Comment by strengejacke** [comment]
I don't think so, I think we had all backports in a file that also had this name

**Comment by strengejacke** [comment]
https://github.com/easystats/insight/blob/main/R/backports.R

**Pull request merged**
