### PR TITLE
format_ci() compatible with bayestestR's objects

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
Convenient for printing in-line stuff:

``` r
insight::format_ci(bayestestR::ci(rnorm(1000)))
#> [1] "95% CI [-1.84, 1.93]"
```

<sup>Created on 2024-02-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
We could improve it with a potential `type="default"` argument that would be `"CI"` in most cases, but with bayestestR objects would be switched to `"HDI"` or `"ETI"` for instance

**Comment by strengejacke** [comment]
> ```r
> bayestestR::ci(rnorm(1000))
> ```

We could simply decide based on the class and then handle inside `format_ci.bayestestR_ci()`.

``` r
class(bayestestR::ci(rnorm(1000)))
#> [1] "bayestestR_eti" "see_eti"        "bayestestR_ci"  "see_ci"        
#> [5] "data.frame"
class(bayestestR::ci(rnorm(1000), method = "HDI"))
#> [1] "bayestestR_hdi" "see_hdi"        "bayestestR_ci"  "see_ci"        
#> [5] "data.frame"
```

<sup>Created on 2024-02-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by DominiqueMakowski** [comment]
yes but it would be nice to be able to overwrite, as in even though it's HDI sometimes people would want to still print CI

**Comment by strengejacke** [comment]
``` r
insight::format_ci(bayestestR::ci(rnorm(1000)))
#> [1] "95% ETI [-1.95, 1.90]"
insight::format_ci(bayestestR::ci(rnorm(1000), method = "HDI"))
#> [1] "95% HDI [-1.87, 1.99]"
insight::format_ci(bayestestR::ci(rnorm(1000)), ci_string = "CI")
#> [1] "95% CI [-1.95, 1.85]"
```

<sup>Created on 2024-02-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Pull request merged**
