### PR TITLE
get_predicted() for svyglm

### PR DESCRIPTION
**Pull request by strengejacke**
Looks good so far:

``` r
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
library(insight)

data(api)
dstrat <- svydesign(
  id = ~1,
  strata = ~stype,
  weights = ~pw,
  data = apistrat,
  fpc = ~fpc
)

m1 <- svyglm(api00 ~ ell + meals + mobility, design = dstrat)
d <- get_datagrid(m1, "ell")

predict(m1, newdata = d, se.fit = TRUE)
#>      link      SE
#> 1  683.24  8.9920
#> 2  678.75  6.0514
#> 3  674.26  4.3761
#> 4  669.78  5.3338
#> 5  665.29  8.0323
#> 6  660.81 11.2851
#> 7  656.32 14.7294
#> 8  651.84 18.2573
#> 9  647.35 21.8281
#> 10 642.87 25.4239
get_predicted(m1, data = d, predict = "link") |> as.data.frame()
#>    Predicted        SE   CI_low  CI_high
#> 1   683.2356  8.992014 665.5010 700.9703
#> 2   678.7502  6.051400 666.8152 690.6851
#> 3   674.2647  4.376143 665.6338 682.8956
#> 4   669.7792  5.333842 659.2594 680.2990
#> 5   665.2937  8.032257 649.4520 681.1355
#> 6   660.8083 11.285056 638.5511 683.0654
#> 7   656.3228 14.729422 627.2724 685.3731
#> 8   651.8373 18.257254 615.8291 687.8455
#> 9   647.3518 21.828120 604.3009 690.4027
#> 10  642.8664 25.423893 592.7236 693.0091

predict(m1, newdata = d, type = "response", se.fit = TRUE)
#>    response      SE
#> 1    683.24  8.9920
#> 2    678.75  6.0514
#> 3    674.26  4.3761
#> 4    669.78  5.3338
#> 5    665.29  8.0323
#> 6    660.81 11.2851
#> 7    656.32 14.7294
#> 8    651.84 18.2573
#> 9    647.35 21.8281
#> 10   642.87 25.4239
get_predicted(m1, data = d) |> as.data.frame()
#>    Predicted        SE   CI_low  CI_high
#> 1   683.2356  8.992014 665.5010 700.9703
#> 2   678.7502  6.051400 666.8152 690.6851
#> 3   674.2647  4.376143 665.6338 682.8956
#> 4   669.7792  5.333842 659.2594 680.2990
#> 5   665.2937  8.032257 649.4520 681.1355
#> 6   660.8083 11.285056 638.5511 683.0654
#> 7   656.3228 14.729422 627.2724 685.3731
#> 8   651.8373 18.257254 615.8291 687.8455
#> 9   647.3518 21.828120 604.3009 690.4027
#> 10  642.8664 25.423893 592.7236 693.0091


m1 <- svyglm(awards ~ ell + meals + mobility, design = dstrat, family = binomial())
#> Warning in eval(family$initialize): non-integer #successes in a binomial glm!
d <- get_datagrid(m1, "ell")

predict(m1, newdata = d, se.fit = TRUE)
#>       link     SE
#> 1  0.47336 0.2882
#> 2  0.52086 0.2060
#> 3  0.56836 0.1559
#> 4  0.61585 0.1694
#> 5  0.66335 0.2357
#> 6  0.71084 0.3240
#> 7  0.75834 0.4206
#> 8  0.80583 0.5209
#> 9  0.85333 0.6231
#> 10 0.90083 0.7264
get_predicted(m1, data = d, predict = "link") |> as.data.frame()
#>    Predicted        SE      CI_low   CI_high
#> 1  0.4733639 0.2882245 -0.09509189 1.0418197
#> 2  0.5208598 0.2059922  0.11458797 0.9271316
#> 3  0.5683556 0.1558953  0.26088846 0.8758228
#> 4  0.6158515 0.1693663  0.28181581 0.9498872
#> 5  0.6633473 0.2357491  0.19838701 1.1283077
#> 6  0.7108432 0.3240084  0.07181200 1.3498744
#> 7  0.7583391 0.4205904 -0.07117775 1.5878559
#> 8  0.8058349 0.5208860 -0.22149166 1.8331615
#> 9  0.8533308 0.6231045 -0.37559809 2.0822596
#> 10 0.9008266 0.7264347 -0.53189696 2.3335502

predict(m1, newdata = d, type = "response", se.fit = TRUE)
#>    response     SE
#> 1   0.61618 0.0682
#> 2   0.62735 0.0482
#> 3   0.63838 0.0360
#> 4   0.64927 0.0386
#> 5   0.66001 0.0529
#> 6   0.67059 0.0716
#> 7   0.68099 0.0914
#> 8   0.69122 0.1112
#> 9   0.70127 0.1305
#> 10  0.71112 0.1492
get_predicted(m1, data = d) |> as.data.frame()
#>    Predicted         SE    CI_low   CI_high
#> 1  0.6161796 0.06816575 0.4762449 0.7392010
#> 2  0.6273488 0.04815734 0.5286157 0.7164930
#> 3  0.6383837 0.03598842 0.5648547 0.7059559
#> 4  0.6492744 0.03856761 0.5699913 0.7210925
#> 5  0.6600119 0.05290120 0.5494347 0.7555265
#> 6  0.6705874 0.07157342 0.5179453 0.7941091
#> 7  0.6809930 0.09136970 0.4822131 0.8303142
#> 8  0.6912212 0.11117501 0.4448524 0.8621379
#> 9  0.7012654 0.13053557 0.4071890 0.8891669
#> 10 0.7111193 0.14923048 0.3700746 0.9116178
```

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by strengejacke** [comment]
@vincentarelbundock @bwiernik How would you validate the CI? predictions and SEs look good, but almost no `predict()` method of other packages returns confidence intervals. Using any other packages for validating the results? Or rely on ~ 1.96 * SE, and give a message about the approx. for CI, similar to what we do in _parameters_?

**Comment by vincentarelbundock** [comment]
> @vincentarelbundock @bwiernik How would you validate the CI? predictions and SEs look good, but almost no `predict()` method of other packages returns confidence intervals. Using any other packages for validating the results? Or rely on ~ 1.96 * SE, and give a message about the approx. for CI, similar to what we do in _parameters_?

Difficult problem. Ideally we would run this in Stata and compare, but as I have found recently, this is *extremely* burdensome. Second best might be to do a few entirely manual conversions: (1) predict on the link, (2) apply a manual transformation with the "raw" `R` function (e.g., `exp()`) instead of the `insight` magic.

The idea there is mostly to write down explicitly what the expected backtransform is for the main models.

**Comment by strengejacke** [comment]
different question; how do I update this branch from the latest commit in #501 ?

**Comment by vincentarelbundock** [comment]
I'm not great at git merges, sorry. My hunch would be to merge the branch that is most similar to current master. That way there is less risk of reverting everything back to the old ways.

**Comment by bwiernik** [comment]
Checkout this branch. Then `merge otherBranch`

**Pull request merged**
