### PR TITLE
fixed issue #208

### PR DESCRIPTION
**Pull request by iago-pssjd**
fix issue #208 

Previously:  
```
> tfit <- glmmTMB(am ~ disp:wt + (1|gear) + wt + (1|carb), data = mtcars)
> find_formula(tfit)
$conditional
am ~ disp:wt
<environment: 0x55ab245aaab8>

$random
$random[[1]]
~1 | gear
<environment: 0x55ab24794290>

$random[[2]]
~1 | carb
<environment: 0x55ab248b0f20>
```
Now should be (I just checked `.get_fixed_effects` on `$conditional`)
```
> tfit <- glmmTMB(am ~ disp:wt + (1|gear) + wt + (1|carb), data = mtcars)
> find_formula(tfit)
$conditional
am ~ disp:wt  + wt
<environment: 0x55ab245aaab8>

$random
$random[[1]]
~1 | gear
<environment: 0x55ab24794290>

$random[[2]]
~1 | carb
<environment: 0x55ab248b0f20>
```
These small corrections may have to be performed also inside first `if (length(f) > 2 && starts_with_parantheses && has_bar)`

### CODE REVIEW

**Comment by strengejacke** [comment]
Thanks I'm currently on vacation, so it'll probably take two weeks for me to check.

**Comment by strengejacke** [comment]
Looking at the checks from the current master and this dev, your PR seems to break existing code... will check.

**Comment by iago-pssjd** [comment]
I know, It could be, but I tried locally to build the package without my changes and the `check` already produced some 'Failed` messages (the same that after my changes). Couldn't be another change in the development version?

Thank you.

**Comment by strengejacke** [comment]
No, there is no "dev" version, but only the latest master-build (which is the master-branch on GitHub). Running the example from `?find_terms`, this works with master:

``` r
library(insight)
library(lme4)
data(sleepstudy)
m <- lmer(
  log(Reaction) ~ Days + I(Days^2) + (1 + Days + exp(Days) | Subject),
  data = sleepstudy
)
find_terms(m)
#> $response
#> [1] "log(Reaction)"
#> 
#> $conditional
#> [1] "Days"      "I(Days^2)"
#> 
#> $random
#> [1] "Days"      "exp(Days)" "Subject"
```

The version with your PR yields this error:

``` r
library(insight)
library(lme4)
data(sleepstudy)
m <- lmer(
  log(Reaction) ~ Days + I(Days^2) + (1 + Days + exp(Days) | Subject),
  data = sleepstudy
)
find_terms(m)
#> Error in parse(text = x, keep.source = FALSE): <text>:1:44: unexpected ')'
#> 1: log(Reaction) ~ Days + I(Days^2)  | Subject)
#>                                                ^
```

<sup>Created on 2020-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


I think your issue is also related to https://github.com/easystats/insight/issues/79

**Comment by strengejacke** [comment]
regular expressions are frustrating...

**Comment by iago-pssjd** [comment]
Ok!, I meant the master-branch on GitHub for dev version. I see that I introduce new problems...

**Comment by iago-pssjd** [comment]
In your example I see that my regex captures `(1 + Days + exp(Days)` as a RE, so I'll think....

Please test with my example too:
```
tfit <- glmmTMB(am ~ disp:wt + (1|gear) + wt + (1|carb), data = mtcars)
```
and also as
```
tfit <- glmmTMB(am ~ (1|gear) + disp:wt + wt + (1|carb), data = mtcars)
```

**Comment by strengejacke** [comment]
should be closed in https://github.com/easystats/insight/commit/9b01a24d2e641d341dcdda00d83ebf0c1b4d4077

**Pull request closed without merging**
