### PR TITLE
Use withr to not change global state

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes https://github.com/easystats/easystats/issues/388

### CODE REVIEW

**Comment by strengejacke** [comment]
@IndrajeetPatil Can I add multiple `test_that()` code chunks into one `withr::*()` call?
Like:

```r
withr::with_environment(
  new.env(),
  m <- lm(...)
  test_that("1", {
    ...
  })
  test_that("2", {
    ...
  })
  test_that("3", {
    ...
  })
)

**Comment by IndrajeetPatil** [comment]
Yes, but IINM you'd need to do something like this:


```r
withr::with_environment(
  new.env(),
  code = {
    m <- lm(...)
    test_that("1", {
      ...
    })
    test_that("2", {
      ...
    })
    test_that("3", {
      ...
    })
  }
)
```

**Comment by strengejacke** [comment]
Cool! This should resolve our scoping issues, and probably also the random test order thing.

**Comment by IndrajeetPatil** [comment]
You could do that, or maybe a better approach is to create a new environment in each test and test the expectations within this scope.

For example, see https://github.com/r-lib/withr/blob/0c5254ebc74590e80cc0056303d74b049b943920/tests/testthat/test-namespace.R#L70-L87

**Comment by strengejacke** [comment]
> You could do that, or maybe a better approach is to create a new environment in each test and test the expectations within this scope.

This is what I would normally do, but if you look at the test structure of _insight_, e.g. https://github.com/easystats/insight/blob/main/tests/testthat/test-lm.R, I would need to re-fit the model every time again for each test then (in those cases where we use `<<-`, which we want to avoid).

**Comment by IndrajeetPatil** [comment]
Maybe add back the removed "random test order" check?

**Comment by strengejacke** [comment]
I think that check should work once we addressed the scoping issues using _withr_, so I'll do that after the withr-work is done.

**Pull request merged**
