### PR TITLE
CRAN submission

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by strengejacke** [comment]
@easystats/core-team I have to update _insight_ due to breaking changes in _glmmTMB_ (see #806), however, there are some strange issues that I get from winbuilder... These issues rather look like false positives, i.e. not related to _insight_? Some failures are from glmmTMB, but then I wonder why we don't see these issues in their tests (https://cran.r-project.org/web/checks/check_results_glmmTMB.html)? (unless this is not tested...)

https://win-builder.r-project.org/aa3Mx7oHVDG0/00check.log

also tagging @bbolker and @mebrooks

**Comment by bbolker** [comment]
Hmm, we certainly can't test everything, but to pick one example out at random (the logs are a little overwhelming), I have no problem with this one:

```
Error ('test-model_info.R:44:3'): glmmTMB bernoulli ─────────────────────────
  Error in `fitTMB(TMBStruc)`: negative log-likelihood is NaN at starting parameter values
  Backtrace:
      ▆
   1. └─glmmTMB::glmmTMB(vs ~ disp + (1 | cyl), data = mtcars, family = binomial()) at test-model_info.R:44:2
   2.   └─glmmTMB::fitTMB(TMBStruc)
```

Whereas locally (with R Under development (unstable) (2023-09-20 r85179), glmmTMB_1.1.8-9000) it seems fine.

```r
glmmTMB::glmmTMB(vs ~ disp + (1 | cyl), data = mtcars, family = binomial())
Formula:          vs ~ disp + (1 | cyl)
Data: mtcars
      AIC       BIC    logLik  df.resid 
 28.69583  33.09304 -11.34792        29 
## etc.
```

I see lots and lots of Matrix-related errors. Maybe see what's going on with that first ... ?

**Comment by strengejacke** [comment]
> I see lots and lots of Matrix-related errors. Maybe see what's going on with that first ... ?

Yes, there are some errors that seem related to the Matrix package, like

```
── Error ('test-cpglmm.R:9:1'): (code run outside of `test_that()`) ────────────
  Error in `mkZt(FL, NULL)`: function 'as_cholmod_sparse' not provided by package 'Matrix'
```

glmmTMB errors, however, also show issues with `glmmTMB::fitTMB(TMBStruc)`?

```r
  ── Error ('test-model_info.R:44:3'): glmmTMB bernoulli ─────────────────────────
  Error in `fitTMB(TMBStruc)`: negative log-likelihood is NaN at starting parameter values
  Backtrace:
      ▆
   1. └─glmmTMB::glmmTMB(vs ~ disp + (1 | cyl), data = mtcars, family = binomial()) at test-model_info.R:44:2
   2.   └─glmmTMB::fitTMB(TMBStruc)
```

**Comment by bbolker** [comment]
I saw those `fitTMB()` errors. There's nothing I can think of off the top of  my head that we caused that  would cause these problems - I will take a quick look to see if I can diagnose, but I was suggesting that you resolve the Matrix problems first on the off chance that the `fitTMB()` errors are actually downstream of them ...

**Comment by bbolker** [comment]
I agree that these are probably false positives. If it were me I would check on r-hub's Windows platforms; if it's OK there then I would submit with a note explaining the issue.

**Comment by bwiernik** [comment]
I rarely use win-builder anymore and just just r-hub's windows servers. I've run into a lot fewer issues like these

**Comment by strengejacke** [comment]
I've never used rhub before 😬 But I just uploaded to rhub, Win-devel, waiting for the result now...

**Comment by strengejacke** [comment]
hm...

https://builder.r-hub.io/status/insight_0.19.5.13.tar.gz-1ef37b183012ae8c430af2446747f2a3#L2566

**Comment by bwiernik** [comment]
Rhub basically runs the CRAN checks with good fidelity--I say it completely replaces the role of win-builder

**Comment by IndrajeetPatil** [comment]
Hmm, I'm wondering why the [GHA windows-devel workflow](https://github.com/easystats/insight/actions/runs/6455362531/job/17601841328?pr=818) doesn't catch the same failures as R-hub. What is R-hub doing differently? Maybe we should also adapt the GHA workflow to align with what R-hub is doing.

**Comment by bbolker** [comment]
I have to say that chasing obscure, heterogeneous test failures across multiple platforms is (by far) my least favourite part of package development ... All three of the windows platforms are reporting **different** errors ...

**Comment by strengejacke** [comment]
Ok, obviously, CRAN checks work slightly different. None of the issues reported by win builder or rhub were mentioned during submission...

**Pull request merged**
